// Builds the Doorstep icon from measurements, and renders every size the app
// ships.
//
// The icon was drawn by eye and it showed. The window's arch and the door's
// arch did not share a centre, so the gap around the glass ran 14 at the top
// and 11 at the sides. The knob sat outside the door's own coordinates, placed
// by position rather than by rule, 0.3 units from the frame. And the whole door
// was scaled and nudged down to fit, which put it off centre.
//
// Here there is one coordinate space and every edge is derived:
//
//   - The door is an arch on a single centre. Its stroke is one weight.
//   - The window's arch shares that centre, so its gap to the frame is the
//     same all the way round, and it is the same gap, GAP, that separates the
//     knob from the frame.
//   - The knob is centred in the panel below the window.
//   - The door is centred on the canvas by its outer edge, so it sits in the
//     middle optically rather than by its path.
//
// Run it after changing any number below:  node tools/icons.mjs

import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import sharp from 'sharp'

const root = join (dirname (fileURLToPath (import.meta.url)), '..', 'apps', 'doorstep', 'public')

// --- the design, in a 100 unit square ---------------------------------------

const BG = '#100e0d'
const FRAME = '#e0954f'
const LIGHT = '#f7cfa4'

const STROKE = 7          // the door's line weight
const HALF_W = 24         // half the door's width, measured on the line's centre
const TOP = 19            // top of the arch, on the line's centre
const BOTTOM = 81         // bottom of the door, on the line's centre
const GAP = 5.5           // one gap: window to frame, and knob to frame
const WINDOW_DROP = 9     // how far the window runs below its arch
const WINDOW_CORNER = 2.5 // the window's lower corners
const KNOB = 4            // knob radius

const cx = 50
const arcY = TOP + HALF_W                 // the arch's centre, shared by the window
const inner = HALF_W - STROKE / 2         // the frame's inside edge, as a radius
const winR = inner - GAP                  // so the window sits GAP inside it everywhere
const winBottom = arcY + WINDOW_DROP
const innerBottom = BOTTOM - STROKE / 2
const knobX = cx + inner - GAP - KNOB     // GAP from the frame's inside edge
const knobY = (winBottom + innerBottom) / 2

const f = (n) => +n.toFixed (3)

function door () {
  const L = cx - HALF_W, R = cx + HALF_W
  return `<path d="M${f (L)} ${f (BOTTOM)} V${f (arcY)} A${f (HALF_W)} ${f (HALF_W)} 0 0 1 ${f (R)} ${f (arcY)} V${f (BOTTOM)} Z" fill="none" stroke="${FRAME}" stroke-width="${STROKE}" stroke-linejoin="round"/>`
}

function windowPane () {
  const L = cx - winR, R = cx + winR, c = WINDOW_CORNER
  return `<path d="M${f (L)} ${f (arcY)} A${f (winR)} ${f (winR)} 0 0 1 ${f (R)} ${f (arcY)} V${f (winBottom - c)} A${c} ${c} 0 0 1 ${f (R - c)} ${f (winBottom)} H${f (L + c)} A${c} ${c} 0 0 1 ${f (L)} ${f (winBottom - c)} Z" fill="${LIGHT}"/>`
}

function knob () {
  return `<circle cx="${f (knobX)}" cy="${f (knobY)}" r="${KNOB}" fill="${LIGHT}"/>`
}

/**
 * @param {object} o
 * @param {boolean} o.rounded  a rounded square, for places that do not mask
 * @param {number}  o.scale    the door's size inside the canvas
 */
function svg ({ rounded, scale = 1 }) {
  const ground = rounded
    ? `<rect width="100" height="100" rx="22" fill="${BG}"/>`
    : `<rect width="100" height="100" fill="${BG}"/>`
  const art = `${windowPane ()}${door ()}${knob ()}`
  const placed = scale === 1 ? art : `<g transform="translate(50 50) scale(${scale}) translate(-50 -50)">${art}</g>`
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">${ground}${placed}</svg>`
}

// --- checks, so a changed number cannot quietly break the rules ---------------

const outerTop = TOP - STROKE / 2
const outerBottom = BOTTOM + STROKE / 2
const checks = {
  'window gap at the top equals the side gap':
    Math.abs ((arcY - winR) - (arcY - inner) - ((cx - winR) - (cx - inner))) < 1e-9,
  'knob sits GAP from the frame':
    Math.abs ((cx + inner) - (knobX + KNOB) - GAP) < 1e-9,
  'knob clears the window':
    knobY - KNOB > winBottom,
  'door is vertically centred':
    Math.abs ((outerTop + outerBottom) / 2 - 50) < 1e-9,
  // A maskable icon is cut to a circle of radius 40; the corners of the door
  // must stay inside it.
  'maskable door stays inside the safe circle':
    Math.hypot (HALF_W + STROKE / 2, outerBottom - 50) * 0.78 < 40,
}
const failed = Object.entries (checks).filter (([, ok]) => !ok)
if (failed.length) {
  console.error ('Icon rules broken:\n  ' + failed.map (([k]) => k).join ('\n  '))
  process.exit (1)
}

// --- write ------------------------------------------------------------------

const favicon = `<!-- Generated by tools/icons.mjs. Edit the numbers there, not this file. -->\n${svg ({ rounded: true })}\n`
writeFileSync (join (root, 'favicon.svg'), favicon)

const renders = [
  // iOS rounds the home screen icon itself; corners already cut would show as
  // black inside its mask, so this one is full bleed.
  { file: 'icon-180.png', size: 180, rounded: false, scale: 1 },
  { file: 'icon-192.png', size: 192, rounded: true, scale: 1 },
  { file: 'icon-512.png', size: 512, rounded: true, scale: 1 },
  // Android crops this to whatever shape the launcher uses, anywhere from a
  // circle to a square, so the door is drawn smaller to survive the tightest.
  { file: 'icon-512-maskable.png', size: 512, rounded: false, scale: 0.78 },
]

for (const r of renders) {
  await sharp (Buffer.from (svg (r)), { density: 72 * (r.size / 100) * 1.2 })
    .resize (r.size, r.size)
    .png ({ compressionLevel: 9 })
    .toFile (join (root, r.file))
  console.log ('wrote', r.file)
}
console.log ('wrote favicon.svg')
console.log ('geometry:', { arcY, windowRadius: winR, knob: [f (knobX), f (knobY)] })
